import fs from 'fs/promises';
import { randomUUID } from 'crypto';
import logger from './logger.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CONFIG_PATH = path.resolve(__dirname, '../prompts/prompts.json');

/**
 * Updates the prompt configuration file.
 * @param {Object} updates - The partial updates containing restaurantId and settings/hours.
 * @returns {Promise<Object>} - The updated configuration object.
 */
export const updateConfig = async (updates) => {
    try {
        logger.info(`📝 Updating config with: ${JSON.stringify(updates, null, 2)}`);

        // 1. Read File
        const fileData = await fs.readFile(CONFIG_PATH, 'utf-8');
        const data = JSON.parse(fileData);

        // 2. Validation
        if (!updates.restaurantId) {
            throw new Error("Missing required field: restaurantId");
        }

        // 3. Find Restaurant by ID
        const restaurantIndex = data.restaurants.findIndex(r => r.restaurantId === updates.restaurantId);

        if (restaurantIndex === -1) {
            throw new Error(`Restaurant not found with ID: ${updates.restaurantId}`);
        }

        const restaurant = data.restaurants[restaurantIndex];

        // 4. Smart Merge
        // Merge settings if provided
        if (updates.settings) {
            restaurant.settings = {
                ...restaurant.settings,
                ...updates.settings
            };
        }

        // Merge operatingHours if provided
        if (updates.operatingHours) {
            restaurant.operatingHours = {
                ...restaurant.operatingHours,
                ...updates.operatingHours
            };
        }

        // Replace questionFlow if provided
        if (updates.questionFlow) {
            restaurant.questionFlow = updates.questionFlow;
        }

        // 5. Update the restaurant in the array
        data.restaurants[restaurantIndex] = restaurant;

        // 6. Write File
        await fs.writeFile(CONFIG_PATH, JSON.stringify(data, null, 2), 'utf-8');

        logger.info(`✅ Config updated successfully for ${restaurant.name}`);
        return restaurant;

    } catch (error) {
        logger.error(`❌ Config Update Error: ${error.message}`);
        throw error;
    }
};

/**
 * Retrieves specific restaurant details from the configuration file.
 * @param {string} restaurantId - The ID of the restaurant.
 * @returns {Promise<Object>} - An object with name, depositAmount, and currency.
 */
export const getRestaurantDetails = async (restaurantId) => {
    try {
        const fileData = await fs.readFile(CONFIG_PATH, 'utf-8');
        const data = JSON.parse(fileData);

        const restaurant = data.restaurants.find(r => r.restaurantId === restaurantId);

        if (!restaurant) {
            throw new Error(`Restaurant not found with ID: ${restaurantId}`);
        }

        return restaurant;
    } catch (error) {
        console.log(`❌ Fetch Details Error: ${error.message}`);
        throw error;
    }
};

// =============================================================================
// QUESTION FLOW HELPERS
// =============================================================================

/**
 * Re-assigns order values as 1, 2, 3 … N based on current array sequence.
 * Mutates the array in-place. Called after every insert or delete.
 */
const normaliseOrders = (questionFlow) => {
    questionFlow.forEach((q, i) => { q.order = i + 1; });
};

/**
 * Adds a new question to a restaurant's questionFlow.
 *
 * Rules:
 *  1. `id` is always auto-generated by the server as q_<uuid>. Never sent by the caller.
 *  2. `order` is always auto-assigned. Never sent by the caller.
 *  3. New question is always placed at the SECOND-LAST position in the array
 *     (just before the last question). If the array has 0 or 1 items, appended at the end.
 *  4. All order values are re-numbered 1, 2, 3 … N after the insertion.
 *
 * @param {string}       restaurantId           - Target restaurant ID.
 * @param {Object}       newQuestion            - Question data from the caller.
 * @param {string}       newQuestion.title      - Human-readable label shown in UI (e.g. "Allergies").
 * @param {string}       newQuestion.botMessage - What the AI says during the call.
 * @param {boolean}      newQuestion.isRequired - Whether the question is mandatory.
 * @param {string|null}  newQuestion.instructions - Optional AI hint. Send null if not needed.
 * @returns {Promise<Object>} Updated restaurant config.
 */
export const addQuestion = async (restaurantId, newQuestion) => {
    try {
        // 1. Validate
        if (!restaurantId) throw new Error('Missing required field: restaurantId');

        const { title, botMessage, isRequired, instructions = null } = newQuestion || {};
        if (!title)      throw new Error('Missing required question field: title');
        if (!botMessage) throw new Error('Missing required question field: botMessage');
        if (isRequired === undefined || isRequired === null) {
            throw new Error('Missing required question field: isRequired');
        }

        // 2. Auto-generate unique id
        const generatedId = `q_${randomUUID()}`;
        logger.info(`➕ Adding question "${title}" (id: ${generatedId}) to restaurant ${restaurantId}`);

        // 3. Read file
        const fileData = await fs.readFile(CONFIG_PATH, 'utf-8');
        const data = JSON.parse(fileData);

        // 4. Find restaurant
        const restaurantIndex = data.restaurants.findIndex(r => r.restaurantId === restaurantId);
        if (restaurantIndex === -1) throw new Error(`Restaurant not found with ID: ${restaurantId}`);

        const restaurant = data.restaurants[restaurantIndex];

        // 5. Sort current flow by order
        const sorted = [...restaurant.questionFlow].sort((a, b) => a.order - b.order);

        // 6. Insert at second-last position
        //    Array of 7 items (index 0–6) → insertAt = 6 → new item slots in before the last one
        //    Array of 0 or 1 items → just append at the end
        const insertAt = sorted.length > 1 ? sorted.length - 1 : sorted.length;
        sorted.splice(insertAt, 0, {
            id: generatedId,
            title,
            botMessage,
            isRequired: Boolean(isRequired),
            instructions,
        });

        // 7. Re-number orders: 1, 2, 3 … N
        normaliseOrders(sorted);
        restaurant.questionFlow = sorted;

        // 8. Write back
        data.restaurants[restaurantIndex] = restaurant;
        await fs.writeFile(CONFIG_PATH, JSON.stringify(data, null, 2), 'utf-8');

        logger.info(`✅ Question "${title}" (id: ${generatedId}) added to "${restaurant.name}"`);
        return restaurant;

    } catch (error) {
        logger.error(`❌ addQuestion Error: ${error.message}`);
        throw error;
    }
};

/**
 * Deletes a question from a restaurant's questionFlow by its id.
 * After deletion, all order values are re-numbered so there are no gaps.
 *
 * @param {string} restaurantId - Target restaurant ID.
 * @param {string} questionId   - The `id` (q_<uuid>) of the question to remove.
 * @returns {Promise<Object>}   Updated restaurant config.
 */
export const deleteQuestion = async (restaurantId, questionId) => {
    try {
        // 1. Validate
        if (!restaurantId) throw new Error('Missing required field: restaurantId');
        if (!questionId)   throw new Error('Missing required field: questionId');

        logger.info(`🗑️ Deleting question "${questionId}" from restaurant ${restaurantId}`);

        // 2. Read file
        const fileData = await fs.readFile(CONFIG_PATH, 'utf-8');
        const data = JSON.parse(fileData);

        // 3. Find restaurant
        const restaurantIndex = data.restaurants.findIndex(r => r.restaurantId === restaurantId);
        if (restaurantIndex === -1) throw new Error(`Restaurant not found with ID: ${restaurantId}`);

        const restaurant = data.restaurants[restaurantIndex];

        // 4. Check the question actually exists
        const exists = restaurant.questionFlow.find(q => q.id === questionId);
        if (!exists) throw new Error(`NOT_FOUND: No question with id "${questionId}" exists`);

        // 5. Remove it
        restaurant.questionFlow = restaurant.questionFlow.filter(q => q.id !== questionId);

        // 6. Re-number orders
        restaurant.questionFlow.sort((a, b) => a.order - b.order);
        normaliseOrders(restaurant.questionFlow);

        // 7. Write back
        data.restaurants[restaurantIndex] = restaurant;
        await fs.writeFile(CONFIG_PATH, JSON.stringify(data, null, 2), 'utf-8');

        logger.info(`✅ Question "${questionId}" deleted from "${restaurant.name}"`);
        return restaurant;

    } catch (error) {
        logger.error(`❌ deleteQuestion Error: ${error.message}`);
        throw error;
    }
};
